### PR TITLE
As a user, I want to be able to specify whether I want the directions to a restaurants by foot or by vehicle.

### PR DESCRIPTION
**Pull request by danidanone17**
## Directions

The directions to a specific restaurant are currently shown only for walking routes. A second option for getting directions for driving has to be added. Both options should be available for choosing by the user. Directions should be drawn on the map according to the selected travel mode.
# Checklist
- [x] Add two buttons for selection of a travel mode
- [x] Make travelMode accessible from outside
- [x] Add toggle effect to the buttons
- [x] Decouple onclick javascript from the html

### CODE REVIEW

**Comment by danidanone17** [comment]
Reviewed, no changes required

**Comment by anna-averianova** [comment]
Can't properly review as I have no maps displayed in my browser.
Other than that, don't know if it is ready yet, but if the button clicking is supposed to work (meaning that if I click on Walking, Driving button gets disabled and vice versa) it doesn't.

**Comment by tdeekens** [comment]
@anna-averianova might that be related to #36 you opened and just be your Firefox? :smile_cat: 
Anyhow, I can click but I don't see a route drawn, the map refreshes though and the button state also changes nicely.

**Comment by tdeekens** [comment]
@ipopova sorry my bad, had auto location services disabled. Seems to work splendidly even in Firefox.

**Comment by anna-averianova** [comment]
@ipopova nevermind, now works.

**Pull request merged**
