### PR TITLE
Improves application's UI being more responsive and intuitive

### LINKED ISSUE #73: As a user I want a responsive application in every view.
Currently parts of the application are broken in their responsive regard, this shall be investigated and fixed.
- Change Layout of flags
- Dishes view and font alignment
- Fixes the big star
- Scroll to top button

### PR DESCRIPTION
**Pull request by tdeekens**
During development the application's responsive nature (it working on tablets and phones too) got a bit left bind. Therefore, this pull-requests deals with changes and improving a few UI related things. 
- [x] Change Layout of flags
- [x] Dishes view and font alignment
- [x] Fixes the big star
- [x] Scroll to top button
- [x] Align bee-line and price in dishes view to top, use same font
- [x] De-uglify the "My Favorites" bar especially the borders
- [ ] <del>Move remove dish button away from add dish button</del>
  - <del>Hard as both are styled by bootstrap as a button-bar</del>
- [x] Add alert to ask if dish should truly be deleted
  - Alerts are so 90s and are yucks on mobile but I'll add one :smile: 
- [x] Remove unused sass styles as nobody cares about 'em

@anna-averianova, @danidanone17, @konstantinos-chronis, @Guido46 feel free to note and add everything UI related you find in the app which bothers you!

Close #73

### CODE REVIEW

**Comment by anna-averianova** [comment]
:heart_eyes: the flags!
I am bothered by the add new dish button. I want it as far away from delete dish as possible. Plus I want Patat to ask me in Windows fashion if I really-really want to delete this dish.

**Comment by anna-averianova** [comment]
Mmm. I think the dish description area could be pimped.  E.g., aligne "Beeline" and restaurant name at the top. Use the same style for "Beeline" and "Price".

**Comment by anna-averianova** [comment]
The borders around the tabs in "My Favorites" are ugly. I made them (just saying).

**Comment by tdeekens** [comment]
@anna-averianova suggestions added to me task list. Check 'em as some seem questionable.

**Pull request merged**
