### PR TITLE
Opening hours2

### PR DESCRIPTION
**Pull request by Guido46**

### CODE REVIEW

**Comment by danidanone17** [comment]
Reviewed

**Comment by Guido46** [comment]
@danidanone17  if you want you can review it ;)

**Comment by danidanone17** [comment]
First of all, please do not merge any changes into master before your changes have been reviewed and accepted by the team. 
- The imbiss view throws an exception because you do not close the  <?php if (count($resultopentimes)>0): ?> properly
- Please remove the ~ files you have committed to the master
- You can avoid this for loop <?php foreach($resultopentimes as $selectedoptim): ?> by making a little change to the finders getOpeningTimeswd() and getOpeningTimeswe() in the OpenTimes model. If you use ->one instead of ->all, you make sure that only one OpenTimes object is returned
- It is not necessary to instantiate the OpenTimes model in the imbiss or dish view over and over again. It is ok, if you do that at the very beginning and than reuse it (you can take a look at how it is done with the comments model)

**Comment by konstantinos-chronis** [comment]
I know it is late, since this is the first time I see a piece of the code, but by looking at Dani's comments the variable names are hard to read. $resultopentimes is 3 words. So the correct name is $resultOpenTimes

**Comment by tdeekens** [comment]
I take parts of the blame for it. I helped John merge it but thought it was reviewed and working. I'll look into this later.

**Pull request merged**
