### PR TITLE
Password field enhancements

### PR DESCRIPTION
**Pull request by konstantinos-chronis**
Ready for review

### CODE REVIEW

**Comment by danidanone17** [comment]
- Please provide comments for each and every function in jquery.pwstrength and rephrase the comment on the overall functionality.
- Where is checked whether the password is between 3 and 30 characters long?
- Why are the strength texts defined two times, one time in jquery.password-strength.js and one time in jquery.pwstrength.js line 61? This is confusing. Please decide on one approach.
- The password strength does not increase if it contains only 1 digit. Why? In general, did you come up with this algorithm yourself or is this a generally known algorithm? 
- The following error message is displayed when switching to this branch and opening the web application: 
  error

**Comment by konstantinos-chronis** [comment]
1) The code is not mine. So I don't think I should provide the comments. Do we provide comments for the library jquery files that we import to the project? 
2) Every fields has a maxlength of 30 characters. The 3 characters minimum is in the validation methods which existed in the project from the beginning
3) They are defined twice, in order to override the default values provided by the lib. I will provide a comment on this, but I will leave the code as it is
4) As I mention in argument 2 it is a fixed algorithm. Similar algorithms follow the same "scoring" approach
5) About the Exception it has nothing to do with me. I didn't touch this peace of code as you can see. I only added some jquery imports and some html code and nothing more.

**Comment by tdeekens** [comment]
(5.) Is related with changes in our User Story related to rendering from the last week's sprint. Every controller wanting to render something needs to `use Scandio\lmvc\modules\rendering\traits;` and then `use traits\RendererController;` the traits with the class. These changes are all in master and I don't know the state of this branch.
For an example of fixing this refer to to the [Application controller](https://github.com/SEP007/lmvc-patat/blob/master/app/controllers/Application.php).

**Comment by tdeekens** [comment]
(3.) The “strength texts” are defined twice as this is the common structure of jQuery plugins. Every plugin, in this case the `jquery.pwstrength.js` has a set of default configuration values. The file then loading in while binding it onto a DOM element for us `jquery.password-strength.js` can overwrite these passing in the `options`-object. If both are really equal, it's redundant. Otherwise its an overwrite of defaults.

**Comment by danidanone17** [comment]
Accepted! :-)

**Pull request merged**
